# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Arrays-Same`
	:runtime-requirement    [ :on "perl 5.008008"^^:CpanId ];
	:runtime-requirement    [ :on "Exporter::Shiny 1.000000"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

